kotlin.mpp.applyDefaultHierarchyTemplate=false

# AtomicFu IR 转换配置
kotlinx.atomicfu.enableJvmIrTransformation=true
kotlinx.atomicfu.enableNativeIrTransformation=true
kotlinx.atomicfu.enableJsIrTransformation=true
kotlin.native.home = /Volumes/sunwarm/project/kmp-test/kotlin-hjc-1030-origin/kotlin-native/dist
